// 播放列表数据
import 'package:melodify_app/models/playlist.dart';
import 'package:melodify_app/models/song.dart';

class MockData {
  MockData._();

static String _albumArt(int id) => 'https://picsum.photos/seed/album$id/400/400';
  static String _playlistImg(int id) =>
      'https://picsum.photos/seed/playlist$id/400/400';

  // 歌曲数据
  static final List<Song> songs = [
    Song(
      id: '1',
      title: 'Midnight Dreams',
      artist: 'Luna Eclipse',
      album: 'Starlight',
      albumArt: _albumArt(1),
      duration: const Duration(minutes: 3, seconds: 45),
      playCount: 1234567,
      isLiked: true,
    ),
    Song(
      id: '2',
      title: 'Electric Waves',
      artist: 'Neon Pulse',
      album: 'Digital Horizon',
      albumArt: _albumArt(2),
      duration: const Duration(minutes: 4, seconds: 12),
      playCount: 987654,
    ),
    Song(
      id: '3',
      title: 'Summer Breeze',
      artist: 'Coastal Vibes',
      album: 'Ocean Songs',
      albumArt: _albumArt(3),
      duration: const Duration(minutes: 3, seconds: 28),
      playCount: 2345678,
      isLiked: true,
    ),
    Song(
      id: '4',
      title: 'City Lights',
      artist: 'Urban Soul',
      album: 'Metropolis',
      albumArt: _albumArt(4),
      duration: const Duration(minutes: 4, seconds: 5),
      playCount: 876543,
    ),
    Song(
      id: '5',
      title: 'Mountain High',
      artist: 'Echo Valley',
      album: 'Nature Calls',
      albumArt: _albumArt(5),
      duration: const Duration(minutes: 5, seconds: 15),
      playCount: 654321,
    ),
    Song(
      id: '6',
      title: 'Rainy Days',
      artist: 'Melancholy Moon',
      album: 'Emotions',
      albumArt: _albumArt(6),
      duration: const Duration(minutes: 3, seconds: 55),
      playCount: 543210,
      isLiked: true,
    ),
    Song(
      id: '7',
      title: 'Dance Floor',
      artist: 'Beat Machine',
      album: 'Club Nights',
      albumArt: _albumArt(7),
      duration: const Duration(minutes: 3, seconds: 32),
      playCount: 1876543,
    ),
    Song(
      id: '8',
      title: 'Acoustic Sunset',
      artist: 'Wooden Strings',
      album: 'Unplugged',
      albumArt: _albumArt(8),
      duration: const Duration(minutes: 4, seconds: 45),
      playCount: 432109,
    ),
    Song(
      id: '9',
      title: 'Future Bass',
      artist: 'Synth Master',
      album: 'Tomorrow',
      albumArt: _albumArt(9),
      duration: const Duration(minutes: 3, seconds: 18),
      playCount: 765432,
    ),
    Song(
      id: '10',
      title: 'Jazz Café',
      artist: 'Smooth Trio',
      album: 'Late Night',
      albumArt: _albumArt(10),
      duration: const Duration(minutes: 5, seconds: 30),
      playCount: 321098,
    ),
    Song(
      id: '11',
      title: 'Rock Anthem',
      artist: 'Thunder Band',
      album: 'Legends',
      albumArt: _albumArt(11),
      duration: const Duration(minutes: 4, seconds: 22),
      playCount: 2109876,
      isLiked: true,
    ),
    Song(
      id: '12',
      title: 'Hip Hop Flow',
      artist: 'Street Poet',
      album: 'Urban Tales',
      albumArt: _albumArt(12),
      duration: const Duration(minutes: 3, seconds: 48),
      playCount: 1543210,
    ),
    Song(
      id: '13',
      title: 'Classical Dreams',
      artist: 'Orchestra One',
      album: 'Symphony',
      albumArt: _albumArt(13),
      duration: const Duration(minutes: 6, seconds: 15),
      playCount: 234567,
    ),
    Song(
      id: '14',
      title: 'Country Road',
      artist: 'Dusty Boots',
      album: 'Homeland',
      albumArt: _albumArt(14),
      duration: const Duration(minutes: 3, seconds: 55),
      playCount: 456789,
    ),
    Song(
      id: '15',
      title: 'EDM Explosion',
      artist: 'Drop Master',
      album: 'Festival',
      albumArt: _albumArt(15),
      duration: const Duration(minutes: 4, seconds: 8),
      playCount: 1987654,
    ),
    Song(
      id: '16',
      title: 'R&B Groove',
      artist: 'Velvet Voice',
      album: 'Soulful',
      albumArt: _albumArt(16),
      duration: const Duration(minutes: 4, seconds: 35),
      playCount: 876543,
      isLiked: true,
    ),
    Song(
      id: '17',
      title: 'Indie Vibes',
      artist: 'Garage Band',
      album: 'DIY',
      albumArt: _albumArt(17),
      duration: const Duration(minutes: 3, seconds: 42),
      playCount: 345678,
    ),
    Song(
      id: '18',
      title: 'Pop Princess',
      artist: 'Star Girl',
      album: 'Spotlight',
      albumArt: _albumArt(18),
      duration: const Duration(minutes: 3, seconds: 25),
      playCount: 3210987,
      isLiked: true,
    ),
    Song(
      id: '19',
      title: 'Metal Thunder',
      artist: 'Iron Storm',
      album: 'Heavy',
      albumArt: _albumArt(19),
      duration: const Duration(minutes: 5, seconds: 45),
      playCount: 654321,
    ),
    Song(
      id: '20',
      title: 'Reggae Sun',
      artist: 'Island Rhythm',
      album: 'Caribbean',
      albumArt: _albumArt(20),
      duration: const Duration(minutes: 4, seconds: 12),
      playCount: 543210,
    ),
  ];

  static final List<Playlist> playlists = [
    Playlist(
      id: 'p1',
      name: 'Today\'s Top Hits',
      description: 'The hottest tracks right now',
      coverImage: _playlistImg(1),
      songs: songs.sublist(0, 10),
      createdBy: 'Melodify',
      createdAt: DateTime(2024, 1, 1),
      followers: 25000000,
    ),
    Playlist(
      id: 'p2',
      name: 'Chill Vibes',
      description: 'Relax and unwind',
      coverImage: _playlistImg(2),
      songs: songs.sublist(2, 8),
      createdBy: 'Melodify',
      createdAt: DateTime(2024, 2, 15),
      followers: 12000000,
    ),
    Playlist(
      id: 'p3',
      name: 'Workout Energy',
      description: 'Power through your workout',
      coverImage: _playlistImg(3),
      songs: songs.sublist(5, 12),
      createdBy: 'Melodify',
      createdAt: DateTime(2024, 3, 1),
      followers: 8500000,
    ),
    Playlist(
      id: 'p4',
      name: 'Late Night Jazz',
      description: 'Smooth jazz for late nights',
      coverImage: _playlistImg(4),
      songs: songs.sublist(8, 14),
      createdBy: 'Melodify',
      createdAt: DateTime(2023, 11, 20),
      followers: 3200000,
    ),
    Playlist(
      id: 'p5',
      name: 'Road Trip',
      description: 'Songs for the open road',
      coverImage: _playlistImg(5),
      songs: songs.sublist(10, 18),
      createdBy: 'Melodify',
      createdAt: DateTime(2024, 4, 10),
      followers: 6700000,
    ),
    Playlist(
      id: 'p6',
      name: 'Focus Flow',
      description: 'Concentration enhancing music',
      coverImage: _playlistImg(6),
      songs: songs.sublist(0, 6),
      createdBy: 'Melodify',
      createdAt: DateTime(2024, 5, 5),
      followers: 9800000,
    ),
    Playlist(
      id: 'p7',
      name: 'Party Starters',
      description: 'Get the party going',
      coverImage: _playlistImg(7),
      songs: songs.sublist(6, 15),
      createdBy: 'Melodify',
      createdAt: DateTime(2024, 1, 15),
      followers: 15000000,
    ),
    Playlist(
      id: 'p8',
      name: 'Acoustic Covers',
      description: 'Beautiful acoustic versions',
      coverImage: _playlistImg(8),
      songs: songs.sublist(7, 13),
      createdBy: 'Melodify',
      createdAt: DateTime(2023, 12, 1),
      followers: 4500000,
    ),
  ];
}
